from  python:3.8
run apt-get update -y&& apt-get install bedtools cmake -y
#run apt-get install build-essential python3-dev -y
#run apt-get install python3-pybedtools -y
run apt-get update
run apt-get install vim -y
run pip install Cython pybedtools -i https://mirrors.ustc.edu.cn/pypi/web/simple
run pip install Circle-Map -i https://mirrors.ustc.edu.cn/pypi/web/simple
run pip install biopython==1.68 -i https://mirrors.ustc.edu.cn/pypi/web/simple
workdir /data
entrypoint []
cmd '/usr/bin/bash'

